### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by Thrasher2020** [JMPerez/spotify-dedup#108]
This has been working well until about 6 hours ago. Now it starts to go through the lists and then pops up with : 

An unexpected error has occurred .

I note it ties in with recent changes.

**Comment by JMPerez** [comment]
Hi @Thrasher2020. It seems to be working fine on my end. The recent changes don’t affect the fetching nor deduplication logic so it should continue functioning.

Can you see if you get any error in the browser’s console?

**Comment by JMPerez** [comment]
Duplicated #109

**Comment by Thrasher2020** [comment]
`framework.ca3e7fa29692f350ed1d.js:1 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ho (https://jmperezperez.com/spotify-dedup/_next/static/chunks/framework.ca3e7fa29692f350ed1d.js:1:99198)
    at Cu (https://jmperezperez.com/spotify-dedup/_next/static/chunks/framework.ca3e7fa29692f350ed1d.js:1:112529)
    at t.unstable_runWithPriority (https://jmperezperez.com/spotify-dedup/_next/static/chunks/framework.ca3e7fa29692f350ed1d.js:1:3942)
    at $l (https://jmperezperez.com/spotify-dedup/_next/static/chunks/framework.ca3e7fa29692f350ed1d.js:1:57296)
    at Su (https://jmperezperez.com/spotify-dedup/_next/static/chunks/framework.ca3e7fa29692f350ed1d.js:1:110381)
    at du (https://jmperezperez.com/spotify-dedup/_next/static/chunks/framework.ca3e7fa29692f350ed1d.js:1:106505)
    at https://jmperezperez.com/spotify-dedup/_next/static/chunks/framework.ca3e7fa29692f350ed1d.js:1:57587
    at t.unstable_runWithPriority (https://jmperezperez.com/spotify-dedup/_next/static/chunks/framework.ca3e7fa29692f350ed1d.js:1:3942)
    at $l (https://jmperezperez.com/spotify-dedup/_next/static/chunks/framework.ca3e7fa29692f350ed1d.js:1:57296)
    at Xl (https://jmperezperez.com/spotify-dedup/_next/static/chunks/framework.ca3e7fa29692f350ed1d.js:1:57532)
lo @ framework.ca3e7fa29692f350ed1d.js:1
i.componentDidCatch.n.callback @ framework.ca3e7fa29692f350ed1d.js:1
hi @ framework.ca3e7fa29692f350ed1d.js:1
co @ framework.ca3e7fa29692f350ed1d.js:1
Cu @ framework.ca3e7fa29692f350ed1d.js:1
t.unstable_runWithPriority @ framework.ca3e7fa29692f350ed1d.js:1
$l @ framework.ca3e7fa29692f350ed1d.js:1
Su @ framework.ca3e7fa29692f350ed1d.js:1
du @ framework.ca3e7fa29692f350ed1d.js:1
(anonymous) @ framework.ca3e7fa29692f350ed1d.js:1
t.unstable_runWithPriority @ framework.ca3e7fa29692f350ed1d.js:1
$l @ framework.ca3e7fa29692f350ed1d.js:1
Xl @ framework.ca3e7fa29692f350ed1d.js:1
Yl @ framework.ca3e7fa29692f350ed1d.js:1
ou @ framework.ca3e7fa29692f350ed1d.js:1
enqueueSetState @ framework.ca3e7fa29692f350ed1d.js:1
w.setState @ framework.ca3e7fa29692f350ed1d.js:1
(anonymous) @ main.tsx:104
(anonymous) @ process.ts:35
value @ process.ts:35
(anonymous) @ process.ts:104
h @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
c @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
c @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
c @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ process.ts:24
value @ main.tsx:106
co @ framework.ca3e7fa29692f350ed1d.js:1
Cu @ framework.ca3e7fa29692f350ed1d.js:1
t.unstable_runWithPriority @ framework.ca3e7fa29692f350ed1d.js:1
$l @ framework.ca3e7fa29692f350ed1d.js:1
Su @ framework.ca3e7fa29692f350ed1d.js:1
du @ framework.ca3e7fa29692f350ed1d.js:1
(anonymous) @ framework.ca3e7fa29692f350ed1d.js:1
t.unstable_runWithPriority @ framework.ca3e7fa29692f350ed1d.js:1
$l @ framework.ca3e7fa29692f350ed1d.js:1
Xl @ framework.ca3e7fa29692f350ed1d.js:1
Yl @ framework.ca3e7fa29692f350ed1d.js:1
ou @ framework.ca3e7fa29692f350ed1d.js:1
enqueueSetState @ framework.ca3e7fa29692f350ed1d.js:1
w.setState @ framework.ca3e7fa29692f350ed1d.js:1
(anonymous) @ index.js:93
h @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
c @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
c @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
c @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
o @ framework.ca3e7fa29692f350ed1d.js:1
p @ framework.ca3e7fa29692f350ed1d.js:1
(anonymous) @ framework.ca3e7fa29692f350ed1d.js:1
y @ framework.ca3e7fa29692f350ed1d.js:1
at @ framework.ca3e7fa29692f350ed1d.js:1
lt @ framework.ca3e7fa29692f350ed1d.js:1
ot @ framework.ca3e7fa29692f350ed1d.js:1
pt @ framework.ca3e7fa29692f350ed1d.js:1
L @ framework.ca3e7fa29692f350ed1d.js:1
W @ framework.ca3e7fa29692f350ed1d.js:1
Jt @ framework.ca3e7fa29692f350ed1d.js:1
Gt @ framework.ca3e7fa29692f350ed1d.js:1
t.unstable_runWithPriority @ framework.ca3e7fa29692f350ed1d.js:1
$l @ framework.ca3e7fa29692f350ed1d.js:1
F @ framework.ca3e7fa29692f350ed1d.js:1
Yt @ framework.ca3e7fa29692f350ed1d.js:1
index.js:351 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ho (https://jmperezperez.com/spotify-dedup/_next/static/chunks/framework.ca3e7fa29692f350ed1d.js:1:99198)
    at Cu (https://jmperezperez.com/spotify-dedup/_next/static/chunks/framework.ca3e7fa29692f350ed1d.js:1:112529)
    at t.unstable_runWithPriority (https://jmperezperez.com/spotify-dedup/_next/static/chunks/framework.ca3e7fa29692f350ed1d.js:1:3942)
    at $l (https://jmperezperez.com/spotify-dedup/_next/static/chunks/framework.ca3e7fa29692f350ed1d.js:1:57296)
    at Su (https://jmperezperez.com/spotify-dedup/_next/static/chunks/framework.ca3e7fa29692f350ed1d.js:1:110381)
    at du (https://jmperezperez.com/spotify-dedup/_next/static/chunks/framework.ca3e7fa29692f350ed1d.js:1:106505)
    at https://jmperezperez.com/spotify-dedup/_next/static/chunks/framework.ca3e7fa29692f350ed1d.js:1:57587
    at t.unstable_runWithPriority (https://jmperezperez.com/spotify-dedup/_next/static/chunks/framework.ca3e7fa29692f350ed1d.js:1:3942)
    at $l (https://jmperezperez.com/spotify-dedup/_next/static/chunks/framework.ca3e7fa29692f350ed1d.js:1:57296)
    at Xl (https://jmperezperez.com/spotify-dedup/_next/static/chunks/framework.ca3e7fa29692f350ed1d.js:1:57532)`

**Comment by abe4mvp** [comment]
i am experiencing the same issue

**Comment by abe4mvp** [comment]
i pulled this and tried it locally and it worked 🤷‍♂️

**Comment by JMPerez** [comment]
This seems to be fixed now.

**Comment by Thrasher2020** [comment]
Hi,

Re-opening as it's doing it again - but only if you choose English as the language. It's fine with any other language.

**Comment by EDM115** [comment]
+1, it indeed works on every other language only
