### ISSUE TITLE
Weird issue upon installation

### ISSUE THREAD

**Issue by alfaplays** [JMPerez/spotify-dedup#161]
-> yarn install

yarn install v1.22.22
error SyntaxError: C:\Users\alfa\Downloads\spotify-dedup-master\package.json: Expected double-quoted property name in JSON at position 424
    at JSON.parse (<anonymous>)
    at C:\Users\alfa\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:1629:59
    at Generator.next (<anonymous>)
    at step (C:\Users\alfa\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:310:30)
    at C:\Users\alfa\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:321:13
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

I have latest version of node and yarn, I remember i've runned your package previously doing the same and it worked fine.

**Comment by JMPerez** [comment]
Closing as not reproducible in the latest version.
